# Generated by Django 3.2.16 on 2023-01-16 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Computer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor', models.TextField()),
                ('title', models.TextField()),
                ('price', models.FloatField()),
                ('striked_price', models.FloatField(blank=True, null=True)),
                ('image_url', models.URLField(blank=True, null=True)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
