# Generated by Django 3.2.16 on 2023-01-16 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('computers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='computer',
            name='price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
