# Generated by Django 3.2.16 on 2023-01-16 06:21
import json
from pathlib import Path

from django.db import migrations


def forward(apps, schema_editor):
    def convert_price_str_to_float(price):
        if not price:
            return None
        return float(price.strip('$').replace(',', ''))

    Computer = apps.get_model('computers', 'Computer')
    inventory_path = Path(__file__).parent.joinpath('inventory.json')
    computers = []
    with inventory_path.open() as f:
        for computer_info in json.load(f):
            computer = Computer(title=computer_info['title'],
                                vendor=computer_info['vendor'],
                                price=convert_price_str_to_float(computer_info['price']),
                                striked_price=convert_price_str_to_float(computer_info['striked-price']),
                                image_url=computer_info['image'])
            computers.append(computer)
    Computer.objects.bulk_create(computers)


def backward(apps, schema_editor):
    Computer = apps.get_model('computers', 'Computer')
    for computer in Computer.objects.all():
        computer.delete()


class Migration(migrations.Migration):
    dependencies = [
        ('computers', '0002_alter_computer_price'),
    ]

    operations = [
        migrations.RunPython(forward, backward),
    ]
